name: Setup Go

description: Sets up Go with the version listed in .tool-versions

runs:
  using: composite

  steps:
    - id: tool-versions
      run: awk '{ print $1"="$2 }' .tool-versions >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.tool-versions.outputs.golang }}
        cache: true
