name: Setup Go

description: Sets up Go with the version listed in .tool-versions

runs:
  using: composite

  steps:
    - id: tool-versions
      run: awk '{ print "::set-output name="$1"::"$2 }' .tool-versions
      shell: bash

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.tool-versions.outputs.golang }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: v2-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          v2-${{ runner.os }}-go-
