name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - id: tool-versions
        run: awk '{ print $1"="$2 }' .tool-versions >> $GITHUB_OUTPUT
        shell: bash
      - uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          version: v${{ steps.tool-versions.outputs.golangci-lint }}
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Test
        run: make test
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate config
        run: npx --package renovate renovate-config-validator
  package:
    needs: [static-analysis, go-mod-tidy, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - id: tool-versions
        run: awk '{ print $1"="$2 }' .tool-versions >> $GITHUB_OUTPUT
        shell: bash
      - uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          version: "v${{ steps.tool-versions.outputs.goreleaser }}"
          install-only: true
      - name: Package binaries
        run: make package
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
