name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          skip-go-installation: true
          skip-pkg-cache: true
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - name: Install gotestsum
        run: go get gotest.tools/gotestsum
      - name: Test
        run: make test
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Renovate config
        run: npx --package renovate renovate-config-validator
  package:
    needs: [static-analysis, go-mod-tidy, test]
    # Run the build on macOS, because only the macOS version is built with CGO enabled.
    # See https://github.com/golang/go/issues/12524
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.183.0
          install-only: true
      - name: Package binaries
        run: make package
