name: Dry-run Renovate

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.json5
      - .github/workflows/dry-run-renovate.yml

permissions:
  contents: read

jobs:
  renovate-dry-run:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
