name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  release:
    # Run the build on macOS, because only the macOS version is built with CGO enabled.
    # See https://github.com/golang/go/issues/12524
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: v0.183.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_ACCOUNT_PAT }}
